server:
  port: 8040

spring:
  application:
    name: mall-user  #微服务名称

  cloud:
    #openfeign的配置
    nacos:
      discovery:
        server-addr: 192.168.101.10:8848
        #server-addr: 192.168.65.174:8848,192.168.65.192:8848,192.168.65.204:8848
         # nacos中服务的注册和发现是使用namespace进行隔离的, 不同namespace之间的服务是不能发现的, 服务隔离用namespace
#        namespace: bc50d386-8870-4a26-8803-0187486c57be
         # nacos中的配置中心是以group组名进行隔离的, 配置隔离用group
#        group: tulingshop
        # 加集群名称, 可以配置负载均衡策略, 实现本地集群中的实例优先调用
        cluster-name: SH
        # 持久化实例: 基础服务数据库, 缓存配置为持久实例, 而上层的业务实例配置为临时实例, 临时实例需要能够自动摘除不健康实例
        # 其实基础服务一般也不会注册到nacos中,所以一般用的临时实例
#        ephemeral: false
        # nacos为了安全,不要部署到外网,且要用用户名密码登录
        username: nacos
        password: nacos

    #openfeign的配置
    openfeign:
      client:
        refresh-enabled: true # 启动刷新功能, 这样可以动态刷新connectTimeOut和readTimeout
        config:
          #          default: # 全局生效
          #            loggerLevel: BASIC
          mall-order:  # 对应微服务
            loggerLevel: FULL
            # 连接超时时间
            connectTimeout: 3000
            # 请求处理超时时间
            readTimeout: 5000
            # 配置编解码器
            encoder: feign.jackson.JacksonEncoder
            decoder: feign.jackson.JacksonDecoder
            requestInterceptors: #配置拦截器
              - com.one.user.interceptor.FeignAuthRequestInterceptor
      httpclient:  #feign client使用 Apache HttpClient5
        hc5:
          enabled: true
      #      okhttp:       #feign client使用 okhttp
      #        enabled: true
      compression: # 配置 GZIP 来压缩数据
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 1024  # 最小请求压缩阈值
        response:
          enabled: true

logging:
  level:
    com.one.user.feign: debug   #打印openFegin日志



management:
  endpoints:
    web:
      exposure:
        include: '*'


