server:
  port: 8090
spring:
  application:
    name: springsecurity-demo
    #datasource 数据源   用的Hikari数据库连接词
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    # 采用配置文件的方式对用户名和密码进行配置, 太简单了通常不使用
#    user:
#      name: root
#      password: 12345678
#      roles: admin


# mybatis-plus配置
mybatis-plus:
  # 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
  mapper-locations:
    - classpath:mapper/**/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.on.springsecuritydemo.pojo
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型: 自增主键
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    # 默认值为false, 会导致返回map value为空字段不显示
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志