server:
  port: 9095

# 以配置文件的方式指定spring security的登录用户名和密码, 通常不使用
#spring:
#  # Spring Security 配置项，对应 SecurityProperties 配置类
#  security:
#    user:
#      name: user   # 用户名
#      password: 123456  # 密码
#      roles:   # 拥有角色
#        - admin