server:
  port: 9001
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

redisson:
  address: redis://127.0.0.1:6379
  password: root
  database: 1

# mybatis配置: 如果是注解,不用以下配置
# 如果是使用mybatis的映射配置文件xml方式: 需要配置以下两行
# mybatis:
#  mapper-locations:      # 指定映射配置文件的类路径
#  type-aliases-package:  # 对映射的实体类进行取别名

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.one.pojo
  # 自定义Mysql的数据类型转换器
  type-handlers-package: com.one.handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

## mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.one.repeatConsume.entity
  #sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true
      ##默认逻辑删除字段
      logic-delete-field: is_delete
